name = "laundry-booking-public"
main = "src/index.ts"
compatibility_date = "2026-05-14"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "laundry-booking"
database_id = "0e48debb-d7a0-4533-ae47-5b91c6f99a69"

[vars]
APP_NAME = "Tvättbokning"
SESSION_COOKIE_NAME = "laundry_session"
SESSION_TTL_SECONDS = "604800"

[triggers]
crons = ["0 3 * * *"]
